### PR TITLE
Add support for nbextension exercise2

### PR DESCRIPTION
**Pull request by Joonalai**
This PR adds support for [nbextension](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/index.html) [exercise2](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/exercise2/readme.html)  by hiding solution cells if they are shown.

### CODE REVIEW

**Comment by KwatME** [comment]
Thanks :) Hope this works well for you.

**Comment by KwatME** [comment]
Hi @Joonalai ,

I'm updating the cool. Please let me know if this is something you still want to keep. I could not find the exercise2 repo to refer to.

Best,
Kwat

**Comment by Joonalai** [comment]
Hi! Yes, I would like to keep these if possible. [Exercise2](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/exercise2/readme.html) is a part of [jupyter_contrib_nbextensions](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/index.html). [Here](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tree/master/src/jupyter_contrib_nbextensions/nbextensions/exercise2) is the relevant part of the repository.

**Comment by KwatME** [comment]
Sounds good @Joonalai

**Pull request merged**
