### PR TITLE
added the ability to support jupyter notebooks created in colab

### PR DESCRIPTION
**Pull request by dan-r95**
jupyter notebooks in google colab have a little bit different meta tag structure
```
(colab notebook)
"metadata": {
    "kernelspec": {
      "display_name": "Python 3",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "codemirror_mode": {
        "name": "ipython",
        "version": 3
      },
```
vs normal notebook
```
"metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
```

 so the
` language = ipynb_dict["metadata"]["language_info"]["name"]` returns an error that the key is not "python" nor "julia" 

Thats why I added a check for the keyword "ipython" to ensure its a python notebook

### CODE REVIEW

**Comment by KwatME** [comment]
Hi @dan-r95 ,

I've updated the tool. I was wondering if you could try it out on colab and make sure it is working the way you like it.

Thanks,
Kwat

**Comment by dan-r95** [comment]
I will have a look!

**Comment by dan-r95** [comment]
Hmm it returns Failed to clean outputs in the console.
Test it with this for example ;) https://colab.research.google.com/github/CSAILVision/semantic-segmentation-pytorch/blob/master/notebooks/DemoSegmenter.ipynb#scrollTo=-IvAYVzTXkcP

**Comment by KwatME** [comment]
Thank you @dan-r95 for catching this.
I will download this notebook and trouble shoot it tonight.

**Pull request merged**
