### PR TITLE
New --black-opt CLI option to provide options to black utility

### PR DESCRIPTION
**Pull request by tristan0x**
This pull-request allows one to provide options to black utility.

Usage example:

```
clean_ipynb --black-opt -S --black-opt -N notebook.ipynb
```

### CODE REVIEW

**Comment by KwatME** [comment]
Thank you again @tristan0x :+1:

**Comment by tristan0x** [comment]
Thanks for merging!
When do you think you can publish a new version on pypi?

**Comment by KwatME** [comment]
Thank you for the awesome addition.

I'm working on it right now :) Hopefully we publish it within 30 minutes.

But there is one thing I would like to discuss with you: do you mind if I rename "opt" to "option"? Everywhere in the code base, we have been using full words instead of abbreviation. We see the elegance of good short abbreviations, yet full word is more specific and minimizes potential misunderstanding. I just wanted to run this idea by you @tristan0x.

Please let me know.

Thanks :)

**Comment by KwatME** [comment]
Done :1st_place_medal: 

Merci :beers:

**Pull request merged**
